import type { Institute, Course, Review, CourseCategory } from "./types"

export const mockInstitutes: Institute[] = [
  {
    id: "1",
    email: "contact@techpro.edu",
    name: "TechPro Academy",
    role: "institute",
    instituteName: "TechPro Academy",
    description:
      "Leading IT education provider with industry-expert instructors and hands-on training. We specialize in Full Stack Development, Data Science, and Cloud Computing with 100% placement assistance.",
    logo: "/tech-academy-logo.png",
    coverImage: "/modern-tech-classroom.jpg",
    location: {
      city: "Bangalore",
      state: "Karnataka",
      address: "123 MG Road, Koramangala",
    },
    contact: {
      phone: "+91 98765 43210",
      email: "contact@techpro.edu",
      website: "https://techpro.edu",
    },
    categories: ["IT"],
    rating: 4.8,
    reviewCount: 245,
    establishedYear: 2015,
    verified: true,
    featured: true,
    facilities: ["Smart Classrooms", "Computer Labs", "Library", "Cafeteria", "Wifi Campus"],
    gallery: ["/computer-lab.png", "/modern-classroom.jpg", "/grand-library.png"],
    status: "approved",
    createdAt: new Date("2015-01-15"),
  },
  {
    id: "2",
    email: "info@allencareer.com",
    name: "Allen Career Institute",
    role: "institute",
    instituteName: "Allen Career Institute",
    description:
      "Premier coaching institute for JEE and NEET preparation with proven track record. Over 50,000 successful selections in IIT-JEE and NEET with experienced faculty and comprehensive study material.",
    logo: "/allen-institute-logo.jpg",
    coverImage: "/students-studying-classroom.jpg",
    location: {
      city: "Kota",
      state: "Rajasthan",
      address: "456 Education Hub, Kota",
    },
    contact: {
      phone: "+91 98765 43211",
      email: "info@allencareer.com",
      website: "https://allencareer.com",
    },
    categories: ["JEE", "NEET"],
    rating: 4.9,
    reviewCount: 1520,
    establishedYear: 1988,
    verified: true,
    featured: true,
    facilities: ["AC Classrooms", "Hostel", "Test Series", "Doubt Clearing Sessions", "Study Material"],
    gallery: ["/lecture-hall.png", "/diverse-students-studying.png", "/hostel-facility.jpg"],
    status: "approved",
    createdAt: new Date("1988-06-10"),
  },
  {
    id: "3",
    email: "contact@brightminds.edu",
    name: "Bright Minds Foundation",
    role: "institute",
    instituteName: "Bright Minds Foundation",
    description:
      "Building strong foundations for young learners from Class 6 to 10. Focus on conceptual learning with interactive teaching methods and personalized attention to each student.",
    logo: "/bright-minds-logo.jpg",
    coverImage: "/school-children-learning.jpg",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      address: "789 Learning Street, Andheri",
    },
    contact: {
      phone: "+91 98765 43212",
      email: "contact@brightminds.edu",
      website: "https://brightminds.edu",
    },
    categories: ["Foundation"],
    rating: 4.7,
    reviewCount: 320,
    establishedYear: 2010,
    verified: true,
    featured: false,
    facilities: ["Interactive Boards", "Activity Rooms", "Playground", "Parent Portal", "Online Classes"],
    gallery: ["/interactive-classroom.jpg", "/children-activities.jpg", "/school-playground.jpg"],
    status: "approved",
    createdAt: new Date("2010-03-20"),
  },
  {
    id: "4",
    email: "admin@medprep.edu",
    name: "MedPrep Excellence",
    role: "institute",
    instituteName: "MedPrep Excellence",
    description:
      "Specialized NEET coaching with highly qualified medical professionals as faculty. Small batch sizes ensure personalized attention with regular mock tests and performance tracking.",
    logo: "/medical-education-logo.jpg",
    coverImage: "/medical-students-learning.jpg",
    location: {
      city: "Delhi",
      state: "Delhi",
      address: "321 Medical Hub, Karol Bagh",
    },
    contact: {
      phone: "+91 98765 43213",
      email: "admin@medprep.edu",
      website: "https://medprep.edu",
    },
    categories: ["NEET"],
    rating: 4.6,
    reviewCount: 450,
    establishedYear: 2012,
    verified: true,
    featured: false,
    facilities: ["Biology Lab", "Chemistry Lab", "Digital Library", "Test Center", "Career Counseling"],
    gallery: ["/biology-lab.png", "/chemistry-lab.png", "/study-room.jpg"],
    status: "approved",
    createdAt: new Date("2012-07-15"),
  },
  {
    id: "5",
    email: "hello@codemaster.io",
    name: "CodeMaster Institute",
    role: "institute",
    instituteName: "CodeMaster Institute",
    description:
      "Modern coding bootcamp offering Full Stack Web Development, Mobile App Development, and DevOps courses. Learn by building real-world projects with mentorship from industry professionals.",
    logo: "/coding-bootcamp-logo.jpg",
    coverImage: "/developers-coding.jpg",
    location: {
      city: "Pune",
      state: "Maharashtra",
      address: "567 Tech Park, Hinjewadi",
    },
    contact: {
      phone: "+91 98765 43214",
      email: "hello@codemaster.io",
      website: "https://codemaster.io",
    },
    categories: ["IT"],
    rating: 4.5,
    reviewCount: 180,
    establishedYear: 2018,
    verified: true,
    featured: true,
    facilities: ["Mac Labs", "Project Rooms", "Mentorship", "Job Portal", "24/7 Access"],
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    status: "approved",
    createdAt: new Date("2018-01-10"),
  },
  {
    id: "6",
    email: "info@jeemaster.com",
    name: "JEE Masters Academy",
    role: "institute",
    instituteName: "JEE Masters Academy",
    description:
      "Focused JEE Advanced preparation with IITian faculty. Rigorous curriculum with daily practice problems and weekly tests to ensure consistent improvement.",
    logo: "/placeholder.svg?height=80&width=80",
    coverImage: "/placeholder.svg?height=400&width=1200",
    location: {
      city: "Hyderabad",
      state: "Telangana",
      address: "890 Education Lane, Madhapur",
    },
    contact: {
      phone: "+91 98765 43215",
      email: "info@jeemaster.com",
      website: "https://jeemaster.com",
    },
    categories: ["JEE"],
    rating: 4.7,
    reviewCount: 680,
    establishedYear: 2008,
    verified: true,
    featured: false,
    facilities: ["Physics Lab", "Math Library", "Test Series", "Doubt Sessions", "Study Hall"],
    gallery: [
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
      "/placeholder.svg?height=300&width=400",
    ],
    status: "approved",
    createdAt: new Date("2008-04-12"),
  },
]

export const mockCourses: Course[] = [
  {
    id: "c1",
    instituteId: "1",
    title: "Full Stack Web Development Bootcamp",
    category: "IT",
    description:
      "Comprehensive 6-month program covering HTML, CSS, JavaScript, React, Node.js, and MongoDB. Build 10+ real-world projects.",
    duration: "6 months",
    mode: "hybrid",
    price: 75000,
    discount: 15,
    features: ["Live Classes", "Project-Based Learning", "Career Support", "Lifetime Access", "Industry Mentorship"],
    curriculum: [
      "HTML & CSS Basics",
      "JavaScript Advanced",
      "React & Redux",
      "Node.js & Express",
      "MongoDB & APIs",
      "Deployment & DevOps",
    ],
    startDate: new Date("2025-02-01"),
    capacity: 30,
    enrolled: 22,
    thumbnail: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "c2",
    instituteId: "2",
    title: "JEE Advanced 2-Year Program",
    category: "JEE",
    description:
      "Complete preparation for JEE Main and Advanced with daily classes, test series, and doubt clearing sessions.",
    duration: "2 years",
    mode: "offline",
    price: 200000,
    features: ["Daily Classes", "Study Material", "Weekly Tests", "Performance Analysis", "Doubt Clearing"],
    curriculum: [
      "Physics - Mechanics",
      "Chemistry - Physical",
      "Mathematics - Calculus",
      "Advanced Problem Solving",
      "Mock Tests",
    ],
    startDate: new Date("2025-04-01"),
    capacity: 50,
    enrolled: 45,
    thumbnail: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "c3",
    instituteId: "3",
    title: "Foundation Course - Class 9 & 10",
    category: "Foundation",
    description: "Build strong fundamentals in Mathematics and Science with interactive learning methods.",
    duration: "1 year",
    mode: "offline",
    price: 45000,
    features: ["Small Batches", "Interactive Learning", "Regular Tests", "Parent Updates", "Doubt Sessions"],
    curriculum: ["Mathematics", "Physics", "Chemistry", "Biology", "Mental Ability"],
    startDate: new Date("2025-06-01"),
    capacity: 25,
    enrolled: 18,
    thumbnail: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "c4",
    instituteId: "4",
    title: "NEET Crash Course",
    category: "NEET",
    description: "Intensive 1-year NEET preparation focusing on high-yield topics and exam strategies.",
    duration: "1 year",
    mode: "offline",
    price: 120000,
    features: ["Expert Faculty", "Daily Mock Tests", "Biology Focus", "Revision Classes", "Study Material"],
    curriculum: [
      "Biology - Botany & Zoology",
      "Physics - NEET Focused",
      "Chemistry - Organic & Inorganic",
      "Mock Test Series",
    ],
    startDate: new Date("2025-05-01"),
    capacity: 40,
    enrolled: 35,
    thumbnail: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "c5",
    instituteId: "5",
    title: "React Native Mobile Development",
    category: "IT",
    description: "Learn to build cross-platform mobile applications using React Native and Expo.",
    duration: "3 months",
    mode: "online",
    price: 35000,
    discount: 20,
    features: ["Online Live Classes", "Project Work", "Code Reviews", "Placement Support", "Portfolio Building"],
    curriculum: [
      "React Basics",
      "React Native Fundamentals",
      "Navigation",
      "State Management",
      "API Integration",
      "App Deployment",
    ],
    startDate: new Date("2025-03-01"),
    capacity: 40,
    enrolled: 12,
    thumbnail: "/placeholder.svg?height=200&width=300",
  },
]

export const mockReviews: Review[] = [
  {
    id: "r1",
    instituteId: "1",
    studentId: "s1",
    studentName: "Rahul Sharma",
    rating: 5,
    comment:
      "Excellent teaching methodology and hands-on projects. Got placed at a top tech company within 2 months of course completion. Highly recommended!",
    createdAt: new Date("2024-11-15"),
    helpful: 24,
  },
  {
    id: "r2",
    instituteId: "1",
    studentId: "s2",
    studentName: "Priya Patel",
    rating: 4,
    comment:
      "Great content and supportive instructors. The projects helped me build a strong portfolio. Career support could be improved.",
    createdAt: new Date("2024-10-20"),
    helpful: 18,
  },
  {
    id: "r3",
    instituteId: "2",
    studentId: "s3",
    studentName: "Amit Kumar",
    rating: 5,
    comment:
      "Best coaching for JEE preparation. Faculty is very experienced and the study material is comprehensive. Cleared JEE Advanced with AIR 450!",
    createdAt: new Date("2024-09-05"),
    helpful: 45,
  },
  {
    id: "r4",
    instituteId: "3",
    studentName: "Sneha Reddy",
    studentId: "s4",
    rating: 5,
    comment: "My daughter improved significantly in her grades. Teachers are caring and explain concepts very clearly.",
    createdAt: new Date("2024-12-01"),
    helpful: 12,
  },
  {
    id: "r5",
    instituteId: "4",
    studentName: "Vikram Singh",
    studentId: "s5",
    rating: 4,
    comment: "Good faculty and regular tests. The crash course helped me focus on important topics. Got 620 in NEET!",
    createdAt: new Date("2024-08-10"),
    helpful: 31,
  },
]

export const categories: { name: CourseCategory; icon: string; description: string }[] = [
  { name: "IT", icon: "💻", description: "Software Development, Data Science, Cloud Computing" },
  { name: "JEE", icon: "⚡", description: "Engineering Entrance Exam Preparation" },
  { name: "NEET", icon: "🏥", description: "Medical Entrance Exam Preparation" },
  { name: "Foundation", icon: "📚", description: "School Level Foundation Courses (6-10)" },
  { name: "Banking", icon: "🏦", description: "Banking & Financial Services Exams" },
  { name: "SSC", icon: "📝", description: "Staff Selection Commission Exams" },
  { name: "UPSC", icon: "🎯", description: "Civil Services Examination" },
]
